export type UserRole =
    | 'ADMIN'
    | 'DOCTOR'
    | 'NURSE'
    | 'RECEIPTION' // Matches 'Receiption' in SQL
    | 'RECEPTIONIST'
    | 'CUSTOMER-CARE'
    | 'LABORANTIN'
    | 'LAB_TECH'
    | 'PHARMACIST'
    | 'CASHIER'
    | 'AUDITOR'
    | 'BILLING_OFFICER'
    | 'MANAGER'
    | 'CLINICAL-DIRECTOR'
    | 'CHIEF-NURSE'
    | 'RADIOLOGIST'
    | 'SECURITY'
    | 'HUMAN-RESOURCE'
    | 'COO'
    | 'DAF'
    | 'STORE'
    | 'USER';

export const ROLE_PERMISSIONS = {
    CAN_REGISTER_PATIENT: ['ADMIN', 'RECEIPTION', 'RECEPTIONIST', 'CUSTOMER-CARE'],
    CAN_VIEW_MEDICAL_RECORDS: ['ADMIN', 'DOCTOR', 'NURSE', 'CHIEF-NURSE', 'CLINICAL-DIRECTOR', 'RADIOLOGIST'],
    CAN_PRESCRIBE: ['ADMIN', 'DOCTOR', 'CLINICAL-DIRECTOR'],
    CAN_DISPENSE: ['ADMIN', 'STORE', 'DOCTOR', 'PHARMACIST'],
    CAN_VIEW_LAB: ['ADMIN', 'DOCTOR', 'LABORANTIN', 'LAB_TECH', 'NURSE', 'CLINICAL-DIRECTOR'],
    CAN_BILL: ['ADMIN', 'BILLING_OFFICER', 'CASHIER', 'DAF', 'COO'],
    CAN_MANAGE_USERS: ['ADMIN', 'MANAGER', 'HUMAN-RESOURCE', 'DAF', 'COO'],
} as const;
